version: '3.8'

services:
  # Python Application Service
  app:
    # Replace <YOUR_GITHUB_USERNAME> with your actual username
    image: ghcr.io/marianarm28/devops-workshop-app:latest
    container_name: python-app
    ports:
      - "8000:8000"
    networks:
      - monitor-net
    restart: unless-stopped

  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net

  # Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net
    depends_on:
      - prometheus

# Volumes and Networks definitions
volumes:
  grafana-storage:

networks:
  monitor-net: