# .github/workflows/deploy-monitoring.yml

name: Deploy Monitoring Stack to EC2

on:
  workflow_run:
    # 1. Nombre del pipeline que debe terminar para que este se ejecute
    workflows: ["Deploy Application to EC2"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/taller_devops
            git pull
            docker-compose up -d prometheus grafana