name: Deploy Application to EC2

on:
  workflow_run:
    # 1. Nombre del pipeline que debe terminar para que este se ejecute
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/taller_devops # Replace with your repo folder on EC2
            git pull
            docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.GH_PAT }}
            docker-compose pull app
            docker-compose up -d app